/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

/* Header for class com_pax_jni_emvparam */

#ifndef _Included_com_pax_jni_emvparam
#define _Included_com_pax_jni_emvparam
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pax_jni_emvparam
 * Method:    EMVInitializeParameter
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_pax_jni_emvparam_EMVInitializeParameter
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_pax_jni_emvparam
 * Method:    EMVAddAIDParameter
 * Signature: (Lcom/pax/emv/EMV_APPLIST;)I
 */
JNIEXPORT jint JNICALL Java_com_pax_jni_emvparam_EMVAddAIDParameter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_pax_jni_emvparam
 * Method:    EMVGetAIDParameter
 * Signature: (ILcom/pax/emv/EMV_APPLIST;)I
 */
JNIEXPORT jint JNICALL Java_com_pax_jni_emvparam_EMVGetAIDParameter
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_pax_jni_emvparam
 * Method:    EMVGetTotalAIDNumber
 * Signature: (Ljava/lang/Integer;)I
 */
JNIEXPORT jint JNICALL Java_com_pax_jni_emvparam_EMVGetTotalAIDNumber
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_pax_jni_emvparam
 * Method:    EMVDeleteAIDParameter
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_pax_jni_emvparam_EMVDeleteAIDParameter
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_pax_jni_emvparam
 * Method:    EMVGetParameter
 * Signature: (Lcom/pax/emv/EMV_Parameter;)I
 */
JNIEXPORT jint JNICALL Java_com_pax_jni_emvparam_EMVGetParameter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_pax_jni_emvparam
 * Method:    EMVSetParameter
 * Signature: (Lcom/pax/emv/EMV_Parameter;)I
 */
JNIEXPORT jint JNICALL Java_com_pax_jni_emvparam_EMVSetParameter
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_pax_jni_emvparam
 * Method:    EMVAddCAPK
 * Signature: (Lcom/pax/emv/EMV_CAPK;)I
 */
JNIEXPORT jint JNICALL Java_com_pax_jni_emvparam_EMVAddCAPK
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_pax_jni_emvparam
 * Method:    EMVGetTotalCAPKNumber
 * Signature: (Ljava/lang/Integer;)I
 */
JNIEXPORT jint JNICALL Java_com_pax_jni_emvparam_EMVGetTotalCAPKNumber
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_pax_jni_emvparam
 * Method:    EMVGetCAPK
 * Signature: (ILcom/pax/emv/EMV_CAPK;)I
 */
JNIEXPORT jint JNICALL Java_com_pax_jni_emvparam_EMVGetCAPK
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     com_pax_jni_emvparam
 * Method:    EMVDelCAPK
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_pax_jni_emvparam_EMVDelCAPK
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
